### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by khanh-devos** [khanh-devos/rails-7-recipe#9]
- Team member number: 2
- Link to  the [Kanban board](https://github.com/khanh-devos/rails-7-recipe/projects/1)

**Comment by divinecharlotte** [comment]
Hi  @Team    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Clean code👍 
- Implemented some project requirements   👍 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider following the below requirement while sharing cards to meet the project requirement because currently your cards are very congested and summarized and each card might take a long to be done 👇 
>  Each `task` should be a separate card that:
Has a descriptive title.
Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
Has a description of the task.

_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joskalenda** [comment]
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @khanh-devos , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Tasks assigned
✅ ... Good kanban creation

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by khanh-devos** [comment]
Thank you @divinecharlotte  and @joskalenda
